import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { cp, mkdir } from "node:fs/promises";
import { resolve } from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's GitHub repository.
*/
`;

const prod = process.argv[2] === "production";
const profile = process.argv[3] ?? "dev";
if (profile !== "dev" && profile !== "test") {
  throw new Error(`Unknown Lina build profile: ${profile}`);
}
const outputDirectory = resolve("dist", profile);
const buildTimestamp = new Date().toISOString();

try {
  const context = await esbuild.context({
    banner: {
      js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    define: {
      __LINA_BUILD_TIMESTAMP__: JSON.stringify(buildTimestamp),
      __LINA_BUILD_PROFILE__: JSON.stringify(profile),
    },
    plugins: profile === "dev" ? [{
      name: "exclude-test-profile-features-from-dev",
      setup(build) {
        build.onResolve({ filter: /runtimeTrace\.js$/ }, () => ({ path: resolve("src/runtimeTrace.dev.ts") }));
        build.onResolve({ filter: /^\.\/src\/views\/(m6TestProfileFeatures|m6TestProfileCommands)\.js$/ }, (args) => ({
          path: resolve(`src/views/${args.path.slice("./src/views/".length, -3)}.dev.ts`),
        }));
      },
    }] : [],
    external: [
      "obsidian",
      "electron",
      "node:sqlite",
      "@codemirror/autocomplete",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/view",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      ...builtinModules,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: resolve(outputDirectory, "main.js"),
  });

  console.log("esbuild context created successfully.");

  if (prod) {
    console.log("Running production build...");
    await context.rebuild();
    await mkdir(outputDirectory, { recursive: true });
    await Promise.all([
      cp("manifest.json", resolve(outputDirectory, "manifest.json")),
      cp("styles.css", resolve(outputDirectory, "styles.css")),
    ]);
    if (profile === "dev") await cp(resolve(outputDirectory, "main.js"), "main.js");
    console.log("Production build completed.");
    // process.exit(0); // Removed to see if it changes behavior
  } else {
    console.log("Watching for changes...");
    await context.watch();
  }
  // If we are in production and rebuild succeeded, we should exit.
  // If we are in watch mode, the script will continue running.
  if (prod) {
      console.log("Exiting after production build.");
      process.exit(0);
  }

} catch (error) {
  console.error("Error during esbuild process:", error);
  process.exit(1); // Exit with an error code if something goes wrong
}
