/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's GitHub repository.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinaPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  ollamaUrl: "http://localhost:11434"
};
var LinaSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Lina" });
    new import_obsidian.Setting(containerEl).setName("URL do Ollama").setDesc("Endere\xE7o do servidor Ollama para futuras consultas.").addText(
      (text) => text.setPlaceholder("http://localhost:11434").setValue(this.plugin.settings.ollamaUrl).onChange(async (value) => {
        this.plugin.settings.ollamaUrl = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/vaultScanner.ts
function getVaultMarkdownFiles(vault) {
  return vault.getMarkdownFiles().filter((file) => !file.path.startsWith(".obsidian/"));
}

// src/contentExtractor.ts
function normalizeExcerpt(text, maxLength) {
  const cleaned = text.replace(/\s+/g, " ").trim();
  if (cleaned.length <= maxLength)
    return cleaned;
  return cleaned.slice(0, maxLength).trim() + "...";
}
function countWords(text) {
  const tokens = text.trim().split(/\s+/);
  return tokens.length === 1 && tokens[0] === "" ? 0 : tokens.length;
}
function analyzeContent(content) {
  const charCount = content.length;
  const wordCount = countWords(content);
  const excerpt = normalizeExcerpt(content, 250);
  return { excerpt, charCount, wordCount };
}

// src/indexStore.ts
async function buildIndex(vault) {
  const files = getVaultMarkdownFiles(vault);
  const now = Date.now();
  const entries = [];
  for (const file of files) {
    const content = await vault.read(file);
    const analysis = analyzeContent(content);
    entries.push({
      path: file.path,
      basename: file.name.replace(/\.md$/, ""),
      extension: file.extension,
      mtime: file.stat.mtime,
      indexedAt: now,
      ...analysis,
      contentUpdatedAt: now
    });
  }
  return {
    version: 2,
    entries
  };
}

// main.ts
var LinaPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadDataFromDisk();
    new import_obsidian2.Notice("Lina carregado.");
    this.addCommand({
      id: "testar-plugin",
      name: "Lina: testar plugin",
      callback: () => {
        new import_obsidian2.Notice("Lina est\xE1 ativo.");
      }
    });
    this.addCommand({
      id: "analisar-vault",
      name: "Lina: analisar vault",
      callback: () => {
        const notes = this.app.vault.getMarkdownFiles();
        new import_obsidian2.Notice(`Lina encontrou ${notes.length} notas Markdown.`);
      }
    });
    this.addCommand({
      id: "reconstruir-indice",
      name: "Lina: reconstruir \xEDndice",
      callback: async () => {
        this.indexData = await buildIndex(this.app.vault);
        await this.saveDataToDisk();
        new import_obsidian2.Notice(
          `Lina indexou ${this.indexData.entries.length} notas Markdown.`
        );
      }
    });
    this.addCommand({
      id: "estado-indice",
      name: "Lina: estado do \xEDndice",
      callback: () => {
        var _a;
        const entries = (_a = this.indexData) == null ? void 0 : _a.entries;
        if (!entries || entries.length === 0) {
          new import_obsidian2.Notice("Lina ainda n\xE3o tem \xEDndice criado.");
          return;
        }
        const totalWords = entries.reduce(
          (sum, e) => sum + e.wordCount,
          0
        );
        new import_obsidian2.Notice(
          `Lina tem ${entries.length} notas no \xEDndice, com ${totalWords} palavras analisadas.`
        );
      }
    });
    this.addSettingTab(new LinaSettingTab(this.app, this));
  }
  onunload() {
  }
  /** @deprecated Usa loadDataFromDisk internamente */
  async loadSettings() {
    await this.loadDataFromDisk();
  }
  /** @deprecated Usa saveDataToDisk internamente */
  async saveSettings() {
    await this.saveDataToDisk();
  }
  async loadDataFromDisk() {
    var _a, _b;
    const raw = await this.loadData();
    const data = raw;
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      (_a = data == null ? void 0 : data.settings) != null ? _a : {}
    );
    this.indexData = (_b = data == null ? void 0 : data.index) != null ? _b : void 0;
  }
  async saveDataToDisk() {
    await this.saveData({
      settings: this.settings,
      index: this.indexData
    });
  }
};
