/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the plugin's GitHub repository.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinaPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/ai/types.ts
var DEFAULT_AI_PROVIDER = "ollama";
var DEFAULT_AI_PROVIDER_SETTINGS = {
  provider: DEFAULT_AI_PROVIDER,
  ollamaUrl: "http://localhost:11434",
  chatModel: "llama3",
  embeddingModel: "nomic-embed-text"
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  provider: "ollama",
  // Default provider
  ollamaUrl: DEFAULT_AI_PROVIDER_SETTINGS.ollamaUrl,
  openaiUrl: "",
  // Add default empty URLs for new providers
  anthropicUrl: "",
  geminiUrl: "",
  chatModel: DEFAULT_AI_PROVIDER_SETTINGS.chatModel,
  embeddingModel: DEFAULT_AI_PROVIDER_SETTINGS.embeddingModel,
  embeddingBatchSize: 10,
  checkSyncOnStartup: false,
  updateIndexOnStartup: false
};
var LinaSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Lina" });
    containerEl.createEl("p", {
      text: "Assistente para Obsidian focado em pesquisa, organiza\xE7\xE3o e enriquecimento de notas Markdown."
    });
    const bmcLink = containerEl.createEl("a", {
      href: "https://www.buymeacoffee.com/apinheiro",
      attr: { target: "_blank", rel: "noopener noreferrer" }
    });
    const bmcImg = bmcLink.createEl("img", {
      attr: {
        src: "https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png",
        alt: "Buy Me a Coffee",
        style: "height: 60px !important;width: 217px !important;"
      }
    });
    containerEl.createEl("p", {
      text: "Se o Lina lhe for \xFAtil, pode apoiar o desenvolvimento atrav\xE9s de Buy Me a Coffee."
    });
    new import_obsidian.Setting(containerEl).setName("Provider de IA").setDesc("Selecione o provider de IA a utilizar").addDropdown((dropdown) => {
      dropdown.addOption("ollama", "Ollama (local)").addOption("openrouter", "OpenRouter").addOption("openai", "OpenAI").addOption("anthropic", "Claude / Anthropic").addOption("gemini", "Gemini").setValue(this.plugin.settings.provider).onChange(async (value) => {
        this.plugin.settings.provider = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.provider === "ollama") {
      new import_obsidian.Setting(containerEl).setName("URL do Ollama").setDesc("Endere\xE7o do servidor Ollama para futuras consultas").addText(
        (text) => {
          var _a;
          return text.setPlaceholder("http://localhost:11434").setValue((_a = this.plugin.settings.ollamaUrl) != null ? _a : "").onChange(async (value) => {
            this.plugin.settings.ollamaUrl = value;
            await this.plugin.saveSettings();
          });
        }
      );
    } else if (this.plugin.settings.provider === "openrouter") {
      new import_obsidian.Setting(containerEl).setName("OpenRouter URL").setDesc("Endere\xE7o do servidor OpenRouter").addText(
        (text) => {
          var _a;
          return text.setPlaceholder("https://openrouter.ai/api").setValue((_a = this.plugin.settings.openrouterUrl) != null ? _a : "").onChange(async (value) => {
            this.plugin.settings.openrouterUrl = value;
            await this.plugin.saveSettings();
          });
        }
      );
    } else if (this.plugin.settings.provider === "openai") {
      new import_obsidian.Setting(containerEl).setName("OpenAI URL").setDesc("Endere\xE7o do servidor OpenAI (ex: https://api.openai.com)").addText(
        (text) => {
          var _a;
          return text.setPlaceholder("https://api.openai.com").setValue((_a = this.plugin.settings.openaiUrl) != null ? _a : "").onChange(async (value) => {
            this.plugin.settings.openaiUrl = value;
            await this.plugin.saveSettings();
          });
        }
      );
    } else if (this.plugin.settings.provider === "anthropic") {
      new import_obsidian.Setting(containerEl).setName("Anthropic URL").setDesc("Endere\xE7o do servidor Anthropic (ex: https://api.anthropic.com)").addText(
        (text) => {
          var _a;
          return text.setPlaceholder("https://api.anthropic.com").setValue((_a = this.plugin.settings.anthropicUrl) != null ? _a : "").onChange(async (value) => {
            this.plugin.settings.anthropicUrl = value;
            await this.plugin.saveSettings();
          });
        }
      );
    } else if (this.plugin.settings.provider === "gemini") {
      new import_obsidian.Setting(containerEl).setName("Gemini URL").setDesc("Endere\xE7o do servidor Gemini (ex: https://generativelanguage.googleapis.com)").addText(
        (text) => {
          var _a;
          return text.setPlaceholder("https://generativelanguage.googleapis.com").setValue((_a = this.plugin.settings.geminiUrl) != null ? _a : "").onChange(async (value) => {
            this.plugin.settings.geminiUrl = value;
            await this.plugin.saveSettings();
          });
        }
      );
    }
    new import_obsidian.Setting(containerEl).setName("Modelo de chat").setDesc("Modelo de linguagem para chat/conversa\xE7\xE3o").addText(
      (text) => text.setPlaceholder("gemma4:12b").setValue(this.plugin.settings.chatModel).onChange(async (value) => {
        this.plugin.settings.chatModel = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Modelo de embeddings").setDesc("Modelo para gera\xE7\xE3o de embeddings").addText(
      (text) => text.setPlaceholder("nomic-embed-text").setValue(this.plugin.settings.embeddingModel).onChange(async (value) => {
        this.plugin.settings.embeddingModel = value;
        await this.plugin.saveSettings();
      })
    );
    function clamp(val, min, max) {
      return Math.min(max, Math.max(min, val));
    }
    new import_obsidian.Setting(containerEl).setName("Tamanho do lote de embeddings").setDesc("N\xFAmero m\xE1ximo de notas a processar em cada execu\xE7\xE3o.").addText(
      (text) => text.setPlaceholder("10").setValue(String(this.plugin.settings.embeddingBatchSize || 10)).onChange(async (value) => {
        const num = parseInt(value, 10);
        const clamped = clamp(isNaN(num) ? 10 : num, 1, 50);
        this.plugin.settings.embeddingBatchSize = clamped;
        await this.plugin.saveSettings();
        text.setValue(String(clamped));
      })
    );
    new import_obsidian.Setting(containerEl).setName("Verificar sincroniza\xE7\xE3o ao iniciar").setDesc("Verifica se o \xEDndice est\xE1 desatualizado quando o plugin \xE9 carregado, sem alterar o \xEDndice.").addToggle(
      (toggle) => {
        var _a;
        return toggle.setValue((_a = this.plugin.settings.checkSyncOnStartup) != null ? _a : false).onChange(async (value) => {
          this.plugin.settings.checkSyncOnStartup = value;
          await this.plugin.saveSettings();
        });
      }
    );
    new import_obsidian.Setting(containerEl).setName("Atualizar \xEDndice ao iniciar").setDesc("Atualiza o \xEDndice de forma incremental quando o plugin \xE9 carregado, sem gerar embeddings.").addToggle(
      (toggle) => {
        var _a;
        return toggle.setValue((_a = this.plugin.settings.updateIndexOnStartup) != null ? _a : false).onChange(async (value) => {
          this.plugin.settings.updateIndexOnStartup = value;
          await this.plugin.saveSettings();
        });
      }
    );
    containerEl.createEl("h3", { text: "Apoiar o projeto" });
    containerEl.createEl("p", {
      text: "O Lina \xE9 desenvolvido de forma independente. O apoio atrav\xE9s de Buy Me a Coffee ajuda a manter o desenvolvimento do projeto."
    });
    const supportLink = containerEl.createEl("a", {
      href: "https://www.buymeacoffee.com/apinheiro",
      text: "Apoiar o projeto",
      attr: { target: "_blank", rel: "noopener noreferrer" }
    });
  }
};

// src/vaultScanner.ts
function getVaultMarkdownFiles(vault) {
  return vault.getMarkdownFiles().filter((file) => !file.path.startsWith(".obsidian/"));
}
function scanVault(vault) {
  const files = getVaultMarkdownFiles(vault);
  return files.map((file) => ({
    path: file.path,
    basename: file.name.replace(/\.md$/, ""),
    extension: file.extension,
    mtime: file.stat.mtime
  }));
}

// src/contentExtractor.ts
function normalizeExcerpt(text, maxLength) {
  const cleaned = text.replace(/\s+/g, " ").trim();
  if (cleaned.length <= maxLength)
    return cleaned;
  return cleaned.slice(0, maxLength).trim() + "...";
}
function countWords(text) {
  const tokens = text.trim().split(/\s+/);
  return tokens.length === 1 && tokens[0] === "" ? 0 : tokens.length;
}
function analyzeContent(content) {
  const charCount = content.length;
  const wordCount = countWords(content);
  const excerpt = normalizeExcerpt(content, 250);
  return { excerpt, charCount, wordCount };
}

// src/indexStore.ts
async function buildIndex(vault, previousIndex) {
  const files = getVaultMarkdownFiles(vault);
  const now = Date.now();
  const previousMap = /* @__PURE__ */ new Map();
  if (previousIndex) {
    for (const entry of previousIndex.entries) {
      previousMap.set(entry.path, entry);
    }
  }
  const entries = [];
  for (const file of files) {
    const content = await vault.read(file);
    const analysis = analyzeContent(content);
    const newEntry = {
      path: file.path,
      basename: file.name.replace(/\.md$/, ""),
      extension: file.extension,
      mtime: file.stat.mtime,
      indexedAt: now,
      ...analysis,
      contentUpdatedAt: now
    };
    const previousEntry = previousMap.get(file.path);
    if (previousEntry) {
      preserveEmbeddingIfUnchanged(newEntry, previousEntry);
    }
    entries.push(newEntry);
  }
  return {
    version: 2,
    entries
  };
}
async function updateIndexIncrementally(vault, previousIndex) {
  if (!previousIndex || previousIndex.entries.length === 0) {
    const indexData = await buildIndex(vault);
    return {
      indexData,
      addedCount: indexData.entries.length,
      updatedCount: 0,
      removedCount: 0
    };
  }
  const files = getVaultMarkdownFiles(vault);
  const now = Date.now();
  const previousMap = /* @__PURE__ */ new Map();
  const currentFileMap = /* @__PURE__ */ new Map();
  for (const entry of previousIndex.entries) {
    previousMap.set(entry.path, entry);
  }
  for (const file of files) {
    currentFileMap.set(file.path, file);
  }
  const entries = [];
  let addedCount = 0;
  let updatedCount = 0;
  for (const file of files) {
    const previousEntry = previousMap.get(file.path);
    if (!previousEntry) {
      const content = await vault.read(file);
      const analysis = analyzeContent(content);
      entries.push({
        path: file.path,
        basename: file.name.replace(/\.md$/, ""),
        extension: file.extension,
        mtime: file.stat.mtime,
        indexedAt: now,
        ...analysis,
        contentUpdatedAt: now
      });
      addedCount++;
      continue;
    }
    if (previousEntry.mtime !== file.stat.mtime) {
      const content = await vault.read(file);
      const analysis = analyzeContent(content);
      entries.push({
        path: file.path,
        basename: file.name.replace(/\.md$/, ""),
        extension: file.extension,
        mtime: file.stat.mtime,
        indexedAt: now,
        ...analysis,
        contentUpdatedAt: now
      });
      updatedCount++;
      continue;
    }
    entries.push(previousEntry);
  }
  let removedCount = 0;
  for (const previousEntry of previousIndex.entries) {
    if (!currentFileMap.has(previousEntry.path)) {
      removedCount++;
    }
  }
  return {
    indexData: {
      version: previousIndex.version,
      entries
    },
    addedCount,
    updatedCount,
    removedCount
  };
}
function preserveEmbeddingIfUnchanged(newEntry, previousEntry) {
  if (newEntry.mtime !== previousEntry.mtime)
    return;
  if (!previousEntry.embedding || previousEntry.embedding.length === 0)
    return;
  if (!previousEntry.embeddingModel)
    return;
  if (!previousEntry.embeddingDimension || previousEntry.embeddingDimension <= 0)
    return;
  if (!previousEntry.embeddedAt)
    return;
  newEntry.embedding = previousEntry.embedding;
  newEntry.embeddingModel = previousEntry.embeddingModel;
  newEntry.embeddingDimension = previousEntry.embeddingDimension;
  newEntry.embeddedAt = previousEntry.embeddedAt;
}
function getEmbeddingStats(indexData) {
  const total = indexData.entries.length;
  const withEmbedding = indexData.entries.filter((e) => e.embedding && e.embedding.length > 0).length;
  return { total, withEmbedding };
}
function findEntriesMissingEmbeddings(indexData, embeddingModel, limit = 10) {
  return indexData.entries.filter((entry) => {
    return !entry.embedding || entry.embedding.length === 0 || entry.embeddingModel !== embeddingModel;
  }).slice(0, limit);
}
function updateEntryEmbedding(indexData, path, embedding, model, dimension) {
  const entry = indexData.entries.find((e) => e.path === path);
  if (entry) {
    entry.embedding = embedding;
    entry.embeddingModel = model;
    entry.embeddingDimension = dimension;
    entry.embeddedAt = Date.now();
  }
}

// src/searchModal.ts
var import_obsidian2 = require("obsidian");

// src/indexSearch.ts
function searchIndex(entries, query) {
  const q = query.toLowerCase().trim();
  if (!q)
    return [];
  const basenameMatches = [];
  const pathMatches = [];
  const excerptMatches = [];
  for (const entry of entries) {
    if (entry.basename.toLowerCase().includes(q)) {
      basenameMatches.push({ entry, matchField: "basename" });
    } else if (entry.path.toLowerCase().includes(q)) {
      pathMatches.push({ entry, matchField: "path" });
    } else if (entry.excerpt.toLowerCase().includes(q)) {
      excerptMatches.push({ entry, matchField: "excerpt" });
    }
  }
  const all = [
    ...basenameMatches,
    ...pathMatches,
    ...excerptMatches
  ];
  return all.slice(0, 20);
}

// src/searchModal.ts
var SearchModal = class extends import_obsidian2.Modal {
  constructor(app, indexData) {
    super(app);
    this.indexData = indexData;
    this.setTitle("Lina \u2014 Pesquisar no \xEDndice");
  }
  onOpen() {
    const { contentEl } = this;
    this.queryInput = contentEl.createEl("input", {
      type: "text",
      placeholder: "Pesquisar notas\u2026"
    });
    this.queryInput.addClass("lina-search-input");
    this.queryInput.addEventListener("input", () => this.updateResults());
    this.resultsContainer = contentEl.createDiv("lina-results");
    this.resultsContainer.style.marginTop = "12px";
    setTimeout(() => this.queryInput.focus(), 50);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  updateResults() {
    const query = this.queryInput.value;
    const results = searchIndex(this.indexData.entries, query);
    this.resultsContainer.empty();
    if (query.trim() && results.length === 0) {
      this.resultsContainer.createEl("p", { text: "Nenhum resultado encontrado." });
      return;
    }
    for (const result of results) {
      this.renderResult(result);
    }
  }
  renderResult(result) {
    const { entry } = result;
    const card = this.resultsContainer.createDiv("lina-result-card");
    card.style.marginBottom = "8px";
    card.style.padding = "8px";
    card.style.border = "1px solid var(--background-modifier-border)";
    card.style.borderRadius = "4px";
    card.style.cursor = "pointer";
    card.createEl("strong", { text: entry.basename });
    const pathEl = card.createEl("div");
    pathEl.style.fontSize = "small";
    pathEl.style.color = "var(--text-muted)";
    pathEl.textContent = entry.path;
    const excerptEl = card.createEl("div");
    excerptEl.style.fontSize = "small";
    excerptEl.style.marginTop = "4px";
    excerptEl.textContent = entry.excerpt.slice(0, 150);
    card.addEventListener("click", () => this.openNote(entry));
  }
  openNote(entry) {
    const file = this.app.vault.getAbstractFileByPath(entry.path);
    if (!file) {
      new import_obsidian2.Notice("Nota n\xE3o encontrada no vault.");
      return;
    }
    this.app.workspace.getLeaf().openFile(file);
    this.close();
  }
};

// src/ai/ollamaProvider.ts
var import_obsidian3 = require("obsidian");
async function testOllamaConnection(baseUrl) {
  const normalizedBaseUrl = baseUrl.endsWith("/") ? baseUrl.slice(0, -1) : baseUrl;
  const apiUrl = `${normalizedBaseUrl}/api/tags`;
  try {
    const response = await (0, import_obsidian3.requestUrl)({
      url: apiUrl,
      method: "GET",
      contentType: "application/json"
    });
    if (response.status === 200) {
      const data = response.json;
      const modelNames = data.models.map((model) => model.name);
      return {
        success: true,
        message: "Liga\xE7\xE3o ao Ollama estabelecida.",
        models: modelNames
      };
    } else {
      return {
        success: false,
        message: `Ollama responded with status ${response.status}.`
      };
    }
  } catch (error) {
    console.error("Error testing Ollama connection:", error);
    let errorMessage = "N\xE3o foi poss\xEDvel ligar ao Ollama.";
    if (error instanceof Error) {
      errorMessage = `N\xE3o foi poss\xEDvel ligar ao Ollama: ${error.message}`;
    }
    return {
      success: false,
      message: errorMessage
    };
  }
}
async function generateOllamaEmbedding(baseUrl, model, input) {
  const normalizedBaseUrl = baseUrl.endsWith("/") ? baseUrl.slice(0, -1) : baseUrl;
  const embedUrl = `${normalizedBaseUrl}/api/embed`;
  try {
    let response = await (0, import_obsidian3.requestUrl)({
      url: embedUrl,
      method: "POST",
      contentType: "application/json",
      body: JSON.stringify({
        model,
        input
      })
    });
    if (response.status === 200) {
      const data = response.json;
      if (Array.isArray(data.embeddings) && data.embeddings.length > 0 && Array.isArray(data.embeddings[0])) {
        const dimension = data.embeddings[0].length;
        return {
          success: true,
          message: "Embedding gerado com sucesso.",
          dimension,
          embedding: data.embeddings[0]
        };
      } else {
        console.warn("Resposta do Ollama sem embeddings ou formato inesperado:", data);
      }
    } else {
      console.warn(`Endpoint /api/embed devolveu status ${response.status}.`);
    }
    const fallbackUrl = `${normalizedBaseUrl}/api/embeddings`;
    response = await (0, import_obsidian3.requestUrl)({
      url: fallbackUrl,
      method: "POST",
      contentType: "application/json",
      body: JSON.stringify({
        model,
        prompt: input
      })
    });
    if (response.status === 200) {
      const fallbackData = response.json;
      if (Array.isArray(fallbackData.embedding) && fallbackData.embedding.length > 0) {
        const dimension = fallbackData.embedding.length;
        return {
          success: true,
          message: "Embedding gerado com sucesso.",
          dimension,
          embedding: fallbackData.embedding
        };
      } else {
        console.warn("Embedding devolvido num formato inesperado no fallback:", fallbackData);
        return {
          success: false,
          message: "Embedding devolvido num formato inesperado."
        };
      }
    } else {
      return {
        success: false,
        message: `Ollama respondeu com status ${response.status} no fallback.`
      };
    }
  } catch (error) {
    console.error("Error generating Ollama embedding:", error);
    let errorMessage = "N\xE3o foi poss\xEDvel gerar embedding.";
    if (error instanceof Error) {
      errorMessage = `N\xE3o foi poss\xEDvel gerar embedding: ${error.message}`;
    }
    return {
      success: false,
      message: errorMessage
    };
  }
}

// src/semanticSearchModal.ts
var import_obsidian4 = require("obsidian");

// src/semanticSearch.ts
function cosineSimilarity(a, b) {
  if (a.length !== b.length)
    return 0;
  let dotProduct = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dotProduct += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  const denominator = Math.sqrt(normA) * Math.sqrt(normB);
  if (denominator === 0)
    return 0;
  return dotProduct / denominator;
}
function searchSemanticIndex(entries, queryEmbedding, limit = 10) {
  const queryDimension = queryEmbedding.length;
  const scored = [];
  for (const entry of entries) {
    if (!entry.embedding || entry.embedding.length !== queryDimension)
      continue;
    const score = cosineSimilarity(queryEmbedding, entry.embedding);
    if (score <= 0)
      continue;
    scored.push({ entry, score });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, limit);
}

// src/semanticSearchModal.ts
var SemanticSearchModal = class extends import_obsidian4.Modal {
  constructor(app, entries, ollamaUrl, embeddingModel) {
    super(app);
    this.isSearching = false;
    this.entries = entries;
    this.ollamaUrl = ollamaUrl;
    this.embeddingModel = embeddingModel;
    this.setTitle("Lina \u2014 Pesquisa sem\xE2ntica de teste");
  }
  onOpen() {
    const { contentEl } = this;
    this.queryInput = contentEl.createEl("input", {
      type: "text",
      placeholder: "Escreva a sua pesquisa\u2026"
    });
    this.queryInput.addClass("lina-search-input");
    this.queryInput.style.marginBottom = "8px";
    this.queryInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        this.performSearch();
      }
    });
    this.searchButton = contentEl.createEl("button", {
      text: "Pesquisar"
    });
    this.searchButton.style.marginBottom = "12px";
    this.searchButton.addEventListener("click", () => this.performSearch());
    this.resultsContainer = contentEl.createDiv("lina-results");
    this.resultsContainer.style.marginTop = "12px";
    setTimeout(() => this.queryInput.focus(), 50);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  async performSearch() {
    if (this.isSearching)
      return;
    const query = this.queryInput.value.trim();
    if (!query)
      return;
    this.isSearching = true;
    this.searchButton.setText("A pesquisar\u2026");
    this.searchButton.disabled = true;
    this.resultsContainer.empty();
    this.resultsContainer.createEl("p", { text: "A gerar embedding da pesquisa\u2026" });
    try {
      const status = await generateOllamaEmbedding(
        this.ollamaUrl,
        this.embeddingModel,
        query
      );
      if (!status.success || !status.embedding || !status.dimension) {
        this.resultsContainer.empty();
        this.resultsContainer.createEl("p", {
          text: `Erro ao gerar embedding: ${status.message}`
        });
        return;
      }
      const results = searchSemanticIndex(
        this.entries,
        status.embedding,
        10
      );
      this.resultsContainer.empty();
      if (results.length === 0) {
        this.resultsContainer.createEl("p", {
          text: "Nenhum resultado encontrado para a pesquisa."
        });
        return;
      }
      for (const result of results) {
        this.renderResult(result);
      }
    } catch (error) {
      console.error("Erro na pesquisa sem\xE2ntica:", error);
      this.resultsContainer.empty();
      this.resultsContainer.createEl("p", {
        text: "Ocorreu um erro durante a pesquisa sem\xE2ntica."
      });
    } finally {
      this.isSearching = false;
      this.searchButton.setText("Pesquisar");
      this.searchButton.disabled = false;
    }
  }
  renderResult(result) {
    const { entry, score } = result;
    const card = this.resultsContainer.createDiv("lina-result-card");
    card.style.marginBottom = "8px";
    card.style.padding = "8px";
    card.style.border = "1px solid var(--background-modifier-border)";
    card.style.borderRadius = "4px";
    card.style.cursor = "pointer";
    const headerEl = card.createDiv();
    headerEl.style.display = "flex";
    headerEl.style.justifyContent = "space-between";
    headerEl.style.alignItems = "center";
    headerEl.createEl("strong", { text: entry.basename });
    const scoreEl = headerEl.createEl("span");
    scoreEl.textContent = score.toFixed(2);
    scoreEl.style.fontSize = "small";
    scoreEl.style.color = "var(--text-accent)";
    const pathEl = card.createEl("div");
    pathEl.style.fontSize = "small";
    pathEl.style.color = "var(--text-muted)";
    pathEl.textContent = entry.path;
    const excerptText = entry.excerpt ? entry.excerpt.slice(0, 150) : "";
    if (excerptText) {
      const excerptEl = card.createEl("div");
      excerptEl.style.fontSize = "small";
      excerptEl.style.marginTop = "4px";
      excerptEl.textContent = excerptText;
    }
    card.addEventListener("click", () => this.openNote(entry));
  }
  openNote(entry) {
    const file = this.app.vault.getAbstractFileByPath(
      entry.path
    );
    if (!file) {
      new import_obsidian4.Notice("Nota n\xE3o encontrada no vault.");
      return;
    }
    this.app.workspace.getLeaf().openFile(file);
    this.close();
  }
};

// src/statusModal.ts
var import_obsidian5 = require("obsidian");

// src/indexSyncStatus.ts
function getIndexSyncStatus(vault, indexData) {
  const currentVaultNotes = scanVault(vault);
  const currentVaultMap = /* @__PURE__ */ new Map();
  for (const note of currentVaultNotes) {
    currentVaultMap.set(note.path, note);
  }
  const indexedMap = /* @__PURE__ */ new Map();
  if (indexData) {
    for (const entry of indexData.entries) {
      indexedMap.set(entry.path, entry);
    }
  }
  const newNotes = [];
  const changedNotes = [];
  const removedNotes = [];
  const notesWithoutEmbedding = [];
  const outdatedEmbeddings = [];
  if (!indexData) {
    return {
      totalVaultNotes: currentVaultNotes.length,
      totalIndexedNotes: 0,
      newNotes,
      changedNotes,
      removedNotes,
      notesWithoutEmbedding,
      outdatedEmbeddings
    };
  }
  for (const currentNote of currentVaultNotes) {
    const indexedEntry = indexedMap.get(currentNote.path);
    if (!indexedEntry) {
      newNotes.push(currentNote);
    } else {
      if (currentNote.mtime !== indexedEntry.mtime) {
        changedNotes.push(indexedEntry);
      }
      if (!indexedEntry.embedding || indexedEntry.embedding.length === 0) {
        notesWithoutEmbedding.push(indexedEntry);
      }
      if (indexedEntry.embedding && indexedEntry.embedding.length > 0 && currentNote.mtime !== indexedEntry.mtime) {
        outdatedEmbeddings.push(indexedEntry);
      }
    }
  }
  for (const indexedEntry of indexData.entries) {
    if (!currentVaultMap.has(indexedEntry.path)) {
      removedNotes.push(indexedEntry);
    }
  }
  return {
    totalVaultNotes: currentVaultNotes.length,
    totalIndexedNotes: (indexData == null ? void 0 : indexData.entries.length) || 0,
    newNotes,
    changedNotes,
    removedNotes,
    notesWithoutEmbedding,
    outdatedEmbeddings
  };
}

// src/statusModal.ts
var LinaStatusModal = class extends import_obsidian5.Modal {
  constructor(app, settings, indexData) {
    super(app);
    this.settings = settings;
    this.indexData = indexData;
    this.setTitle("Estado geral do Lina");
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    const providerLabel = this.getProviderLabel(this.settings.provider);
    contentEl.createEl("h3", { text: "Configura\xE7\xE3o" });
    contentEl.createEl("p", {
      text: `Provider de IA: ${providerLabel}`
    });
    contentEl.createEl("p", {
      text: `URL do Ollama: ${this.settings.ollamaUrl || DEFAULT_SETTINGS.ollamaUrl}`
    });
    contentEl.createEl("p", {
      text: `Modelo de chat: ${this.settings.chatModel || DEFAULT_SETTINGS.chatModel}`
    });
    contentEl.createEl("p", {
      text: `Modelo de embeddings: ${this.settings.embeddingModel || DEFAULT_SETTINGS.embeddingModel}`
    });
    contentEl.createEl("h3", { text: "\xCDndice" });
    if (this.indexData && this.indexData.entries.length > 0) {
      const totalNotas = this.indexData.entries.length;
      const totalPalavras = this.indexData.entries.reduce(
        (sum, e) => sum + e.wordCount,
        0
      );
      contentEl.createEl("p", {
        text: `Notas no \xEDndice: ${totalNotas}`
      });
      contentEl.createEl("p", {
        text: `Total de palavras analisadas: ${totalPalavras}`
      });
    } else {
      contentEl.createEl("p", {
        text: "\xCDndice: ainda n\xE3o criado"
      });
    }
    contentEl.createEl("h3", { text: "Embeddings" });
    if (this.indexData && this.indexData.entries.length > 0) {
      const stats = getEmbeddingStats(this.indexData);
      contentEl.createEl("p", {
        text: `Notas com embeddings: ${stats.withEmbedding} de ${stats.total}`
      });
    } else {
      contentEl.createEl("p", {
        text: "\xCDndice n\xE3o dispon\xEDvel"
      });
    }
    contentEl.createEl("p", {
      text: `Tamanho do lote: ${this.settings.embeddingBatchSize || DEFAULT_SETTINGS.embeddingBatchSize}`
    });
    contentEl.createEl("h3", { text: "Sincroniza\xE7\xE3o" });
    this.syncStatusEl = contentEl.createDiv();
    this.updateSyncStatus();
    contentEl.createEl("h3", { text: "Liga\xE7\xE3o" });
    this.ollamaStatusEl = contentEl.createEl("p", {
      text: "Ollama: a verificar\u2026"
    });
    this.checkOllamaConnection();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  async updateSyncStatus() {
    if (!this.indexData || this.indexData.entries.length === 0) {
      this.syncStatusEl.empty();
      this.syncStatusEl.createEl("p", { text: "\xCDndice ainda n\xE3o criado." });
      return;
    }
    const syncStatus = getIndexSyncStatus(this.app.vault, this.indexData);
    this.syncStatusEl.empty();
    this.syncStatusEl.createEl("p", { text: `Notas no vault: ${syncStatus.totalVaultNotes}` });
    this.syncStatusEl.createEl("p", { text: `Notas no \xEDndice: ${syncStatus.totalIndexedNotes}` });
    this.syncStatusEl.createEl("p", { text: `Notas novas: ${syncStatus.newNotes.length}` });
    this.syncStatusEl.createEl("p", { text: `Notas alteradas: ${syncStatus.changedNotes.length}` });
    this.syncStatusEl.createEl("p", { text: `Notas removidas: ${syncStatus.removedNotes.length}` });
    this.syncStatusEl.createEl("p", { text: `Notas sem embedding: ${syncStatus.notesWithoutEmbedding.length}` });
    this.syncStatusEl.createEl("p", { text: `Embeddings possivelmente desatualizados: ${syncStatus.outdatedEmbeddings.length}` });
  }
  async checkOllamaConnection() {
    const ollamaUrl = this.settings.ollamaUrl || DEFAULT_SETTINGS.ollamaUrl;
    if (!ollamaUrl) {
      this.ollamaStatusEl.textContent = "Ollama: URL n\xE3o definida";
      return;
    }
    try {
      const status = await testOllamaConnection(ollamaUrl);
      if (status.success) {
        this.ollamaStatusEl.textContent = "Ollama: estabelecida";
      } else {
        this.ollamaStatusEl.textContent = "Ollama: n\xE3o foi poss\xEDvel ligar";
      }
    } catch (e) {
      this.ollamaStatusEl.textContent = "Ollama: n\xE3o foi poss\xEDvel ligar";
    }
  }
  getProviderLabel(provider) {
    const map = {
      ollama: "Ollama (local)",
      openrouter: "OpenRouter",
      openai: "OpenAI",
      anthropic: "Claude / Anthropic",
      gemini: "Gemini"
    };
    return map[provider] || provider;
  }
};

// main.ts
var LinaPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadDataFromDisk();
    new import_obsidian6.Notice("Lina carregado.");
    this.addCommand({
      id: "testar-plugin",
      name: "Lina: testar plugin",
      callback: () => {
        new import_obsidian6.Notice("Lina est\xE1 ativo.");
      }
    });
    this.addCommand({
      id: "analisar-vault",
      name: "Lina: analisar vault",
      callback: () => {
        const notes = this.app.vault.getMarkdownFiles();
        new import_obsidian6.Notice(`Lina encontrou ${notes.length} notas Markdown.`);
      }
    });
    this.addCommand({
      id: "reconstruir-indice",
      name: "Lina: reconstruir \xEDndice",
      callback: async () => {
        this.indexData = await buildIndex(this.app.vault, this.indexData);
        await this.saveDataToDisk();
        new import_obsidian6.Notice(
          `Lina indexou ${this.indexData.entries.length} notas Markdown.`
        );
      }
    });
    this.addCommand({
      id: "atualizar-indice",
      name: "Lina: atualizar \xEDndice",
      callback: async () => {
        const result = await updateIndexIncrementally(this.app.vault, this.indexData);
        this.indexData = result.indexData;
        await this.saveDataToDisk();
        new import_obsidian6.Notice(
          `\xCDndice atualizado: ${result.addedCount} novas, ${result.updatedCount} alteradas, ${result.removedCount} removidas.`
        );
      }
    });
    this.addCommand({
      id: "estado-indice",
      name: "Lina: estado do \xEDndice",
      callback: () => {
        var _a;
        const entries = (_a = this.indexData) == null ? void 0 : _a.entries;
        if (!entries || entries.length === 0) {
          new import_obsidian6.Notice("Lina ainda n\xE3o tem \xEDndice criado.");
          return;
        }
        const totalWords = entries.reduce(
          (sum, e) => sum + e.wordCount,
          0
        );
        new import_obsidian6.Notice(
          `Lina tem ${entries.length} notas no \xEDndice, com ${totalWords} palavras analisadas.`
        );
      }
    });
    this.addCommand({
      id: "pesquisar-indice",
      name: "Lina: pesquisar no \xEDndice",
      callback: () => {
        if (!this.indexData || this.indexData.entries.length === 0) {
          new import_obsidian6.Notice("Lina ainda n\xE3o tem \xEDndice criado.");
          return;
        }
        new SearchModal(this.app, this.indexData).open();
      }
    });
    this.addCommand({
      id: "testar-ligacao-ollama",
      name: "Lina: testar liga\xE7\xE3o ao Ollama",
      callback: async () => {
        const ollamaUrl = this.settings.ollamaUrl || DEFAULT_SETTINGS.ollamaUrl;
        if (!ollamaUrl) {
          new import_obsidian6.Notice("URL do Ollama n\xE3o definida nas configura\xE7\xF5es.");
          return;
        }
        const status = await testOllamaConnection(ollamaUrl);
        new import_obsidian6.Notice(status.message);
        if (status.success && status.models && status.models.length > 0) {
          console.log("Ollama Models:", status.models);
        }
      }
    });
    this.addCommand({
      id: "testar-embedding",
      name: "Lina: testar embedding",
      callback: async () => {
        const ollamaUrl = this.settings.ollamaUrl || DEFAULT_SETTINGS.ollamaUrl;
        const embeddingModel = this.settings.embeddingModel || DEFAULT_SETTINGS.embeddingModel;
        const inputText = "Teste de embedding do Lina";
        if (!ollamaUrl || !embeddingModel) {
          new import_obsidian6.Notice("URL do Ollama ou modelo de embedding n\xE3o definidos nas configura\xE7\xF5es.");
          return;
        }
        const status = await generateOllamaEmbedding(ollamaUrl, embeddingModel, inputText);
        if (status.success && status.dimension) {
          new import_obsidian6.Notice(`Embedding gerado com sucesso. Dimens\xE3o: ${status.dimension}.`);
        } else {
          new import_obsidian6.Notice(`N\xE3o foi poss\xEDvel gerar embedding. ${status.message}`);
        }
      }
    });
    this.addCommand({
      id: "gerar-embeddings-teste",
      name: "Lina: gerar embeddings",
      callback: async () => {
        if (!this.indexData || this.indexData.entries.length === 0) {
          new import_obsidian6.Notice("Lina ainda n\xE3o tem \xEDndice criado.");
          return;
        }
        const ollamaUrl = this.settings.ollamaUrl || DEFAULT_SETTINGS.ollamaUrl;
        const embeddingModel = this.settings.embeddingModel || DEFAULT_SETTINGS.embeddingModel;
        if (!ollamaUrl || !embeddingModel) {
          new import_obsidian6.Notice("URL do Ollama ou modelo de embedding n\xE3o definidos nas configura\xE7\xF5es.");
          return;
        }
        const batchSize = this.settings.embeddingBatchSize || 10;
        const entriesToProcess = findEntriesMissingEmbeddings(this.indexData, embeddingModel, batchSize);
        if (entriesToProcess.length === 0) {
          new import_obsidian6.Notice("Todas as notas j\xE1 t\xEAm embedding para o modelo atual.");
          return;
        }
        let processedCount = 0;
        for (const entry of entriesToProcess) {
          const text = entry.excerpt || entry.basename;
          if (!text)
            continue;
          const status = await generateOllamaEmbedding(ollamaUrl, embeddingModel, text);
          if (status.success && status.embedding && status.dimension) {
            updateEntryEmbedding(this.indexData, entry.path, status.embedding, embeddingModel, status.dimension);
            processedCount++;
          }
        }
        if (processedCount > 0) {
          await this.saveDataToDisk();
        }
        const stats = getEmbeddingStats(this.indexData);
        new import_obsidian6.Notice(`Lina gerou embeddings para ${processedCount} notas. Estado: ${stats.withEmbedding} de ${stats.total} notas com embeddings.`);
      }
    });
    this.addCommand({
      id: "estado-embeddings",
      name: "Lina: estado dos embeddings",
      callback: () => {
        if (!this.indexData || this.indexData.entries.length === 0) {
          new import_obsidian6.Notice("Lina ainda n\xE3o tem \xEDndice criado.");
          return;
        }
        const stats = getEmbeddingStats(this.indexData);
        new import_obsidian6.Notice(`Lina tem ${stats.withEmbedding} de ${stats.total} notas com embeddings.`);
      }
    });
    this.addCommand({
      id: "pesquisa-semantica-teste",
      name: "Lina: pesquisa sem\xE2ntica",
      callback: () => {
        if (!this.indexData || this.indexData.entries.length === 0) {
          new import_obsidian6.Notice("Lina ainda n\xE3o tem \xEDndice criado.");
          return;
        }
        const ollamaUrl = this.settings.ollamaUrl || DEFAULT_SETTINGS.ollamaUrl;
        const embeddingModel = this.settings.embeddingModel || DEFAULT_SETTINGS.embeddingModel;
        if (!ollamaUrl || !embeddingModel) {
          new import_obsidian6.Notice("URL do Ollama ou modelo de embedding n\xE3o definidos nas configura\xE7\xF5es.");
          return;
        }
        const entriesWithEmbeddings = this.indexData.entries.filter(
          (e) => e.embedding && e.embedding.length > 0
        );
        if (entriesWithEmbeddings.length === 0) {
          new import_obsidian6.Notice("Lina ainda n\xE3o tem notas com embeddings. Execute primeiro 'Lina: gerar embeddings de teste'.");
          return;
        }
        new SemanticSearchModal(
          this.app,
          this.indexData.entries,
          ollamaUrl,
          embeddingModel
        ).open();
      }
    });
    this.addCommand({
      id: "estado-geral",
      name: "Lina: estado geral",
      callback: () => {
        new LinaStatusModal(this.app, this.settings, this.indexData).open();
      }
    });
    this.addCommand({
      id: "verificar-sincronizacao-indice",
      name: "Lina: verificar sincroniza\xE7\xE3o do \xEDndice",
      callback: () => {
        if (!this.indexData || this.indexData.entries.length === 0) {
          new import_obsidian6.Notice("Lina ainda n\xE3o tem \xEDndice criado.");
          return;
        }
        const syncStatus = getIndexSyncStatus(this.app.vault, this.indexData);
        new import_obsidian6.Notice(
          `Sincroniza\xE7\xE3o: ${syncStatus.newNotes.length} novas, ${syncStatus.changedNotes.length} alteradas, ${syncStatus.removedNotes.length} removidas.`
        );
      }
    });
    this.addSettingTab(new LinaSettingTab(this.app, this));
    void this.runStartupIndexAutomation();
  }
  onunload() {
  }
  /** @deprecated Usa loadDataFromDisk internamente */
  async loadSettings() {
    await this.loadDataFromDisk();
  }
  /** @deprecated Usa saveDataToDisk internamente */
  async saveSettings() {
    await this.saveDataToDisk();
  }
  async loadDataFromDisk() {
    var _a, _b;
    const raw = await this.loadData();
    const data = raw;
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      (_a = data == null ? void 0 : data.settings) != null ? _a : {}
    );
    this.indexData = (_b = data == null ? void 0 : data.index) != null ? _b : void 0;
  }
  async saveDataToDisk() {
    await this.saveData({
      settings: this.settings,
      index: this.indexData
    });
  }
  async runStartupIndexAutomation() {
    if (this.settings.updateIndexOnStartup) {
      const result = await updateIndexIncrementally(this.app.vault, this.indexData);
      const hadPreviousIndex = !!this.indexData && this.indexData.entries.length > 0;
      const hasChanges2 = result.addedCount > 0 || result.updatedCount > 0 || result.removedCount > 0;
      this.indexData = result.indexData;
      if (!hadPreviousIndex) {
        await this.saveDataToDisk();
        new import_obsidian6.Notice(`Lina criou o \xEDndice com ${result.indexData.entries.length} notas.`);
        return;
      }
      if (hasChanges2) {
        await this.saveDataToDisk();
        new import_obsidian6.Notice(
          `Lina atualizou o \xEDndice: ${result.addedCount} novas, ${result.updatedCount} alteradas, ${result.removedCount} removidas.`
        );
      }
      return;
    }
    if (!this.settings.checkSyncOnStartup) {
      return;
    }
    if (!this.indexData || this.indexData.entries.length === 0) {
      new import_obsidian6.Notice("Lina: \xEDndice ainda n\xE3o criado.");
      return;
    }
    const syncStatus = getIndexSyncStatus(this.app.vault, this.indexData);
    const hasChanges = syncStatus.newNotes.length > 0 || syncStatus.changedNotes.length > 0 || syncStatus.removedNotes.length > 0;
    if (hasChanges) {
      new import_obsidian6.Notice(
        `Lina: \xEDndice desatualizado. ${syncStatus.newNotes.length} novas, ${syncStatus.changedNotes.length} alteradas, ${syncStatus.removedNotes.length} removidas.`
      );
    }
  }
};
